method: grid
metric:
  name: eval/episode_reward
  goal: maximize
parameters:
  confounder.body_weights.torso:
    values: [4.5, 5.0, 5.5]
  confounder.friction:
    values: [0.8, 1.0, 1.2]
  confounder.gravity:
    values:
      - [0.0, 0.0, -9.81]
      - [0.0, 0.0, -10.0]
      - [0.0, 0.0, -10.2]
  agent.params.alpha_lr:
    distribution: uniform
    min: 1e-4
    max: 1e-3
  agent.params.actor_lr:
    distribution: uniform
    min: 1e-4
    max: 1e-3
  agent.params.critic_lr:
    distribution: uniform
    min: 1e-4
    max: 1e-3
